apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"mysql-sc"},"parameters":{"fstype":"ext4","storagepolicyname":"Space-Efficient"},"provisioner":"csi.vsphere.vmware.com"}
    storageclass.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2020-06-23T12:55:44Z"
  name: mysql-sc
  resourceVersion: "678347"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/mysql-sc
  uid: da1119f7-b550-11ea-b790-005056808653
parameters:
  fstype: ext4
  storagepolicyname: Space-Efficient
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

