---
- hosts: all
  connection: local
  become: true
  vars:
    fly_version: 5.8.1
    vault_version: 1.3.2
    docker_compose_version: 1.25.5
    helm_version: 3.3.4

  tasks:
  - name: "update package manager"
    package:
      name: '*'
      state: latest
    ignore_errors: yes
    tags:
      - kernel
      - git
      - vault

  - name: "Installing Git"
    package: pkg={{ item }} state=present
    with_items:
      - git
    ignore_errors: yes
    tags:
      - git

  - name: "Installing unzip"
    package: pkg={{ item }} state=present
    with_items:
      - unzip
    ignore_errors: yes
    tags:
      - vault

  - name: Make sure the docker-compose binary is gone first
    file:
      path: /usr/local/bin/docker-compose
      state: absent
    tags:
      - docker-compose

  - name: "Install docker-compose"
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
      dest: /usr/local/bin/docker-compose
      validate_certs: no
      mode: '0755'
    tags:
      - docker-compose

  - name: Make sure the fly binary is gone first
    file:
      path: /usr/local/bin/fly
      state: absent
    tags:
      - fly

  - name: "Installing fly"
    unarchive:
      src: "https://github.com/concourse/concourse/releases/download/v{{ fly_version }}/fly-{{ fly_version }}-{{ ansible_system | lower }}-amd64.tgz"
      dest: /usr/local/bin/
      remote_src: yes
      keep_newer: no
      mode: '0755'
      validate_certs: no
    tags:
      - fly

  - name: Make sure the helm binary is gone first
    file:
      path: /usr/local/bin/helm
      state: absent
    tags:
      - helm

  - name: "Installing helm"
    unarchive:
      src: "https://get.helm.sh/helm-v{{ helm_version }}-{{ ansible_system | lower }}-amd64.tgz"
      dest: /usr/local/bin/
      remote_src: yes
      keep_newer: no
      mode: '0755'
      validate_certs: no
    tags:
      - helm

  - name: Make sure the jq binary is gone first
    file:
      path: /usr/local/bin/jq
      state: absent
    tags:
      - jq

  - name: "Download lastest stable version of jq"
    get_url:
      url: "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
      dest: /usr/local/bin/jq
      mode: '0755'
      validate_certs: no
    tags:
      - jq

  - name: Make sure the vault binary is gone first
    file:
      path: /usr/local/bin/vault
      state: absent
    tags:
      - vault

  - name: "Install vault cli"
    unarchive:
      src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ ansible_system | lower }}_amd64.zip"
      dest: /usr/local/bin/
      remote_src: yes
      keep_newer: no
      mode: '0755'
      validate_certs: no
    tags:
      - vault

  - name: "Disable Centos FireWall Service"
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - docker

  - name: "Disable Ubuntu FireWall Service"
    systemd:
      name: ufw
      state: stopped
      enabled: no
    when: ansible_facts['distribution'] == "Ubuntu"
    tags:
      - docker

  - name: Creates directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
    tags:
      - docker

  - name: Add Docker repo (Centos)
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - docker

  - name: Add Docker Repo (Ubuntu)
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
    tags:
      - docker

  - name: "Install Docker-CE"
    package:
      name: docker-ce
      state: latest
    tags:
      - docker

  - name: "Make sure the service starts at boot and is currently started"
    systemd:
      name: docker
      daemon_reload: yes
      state: started
      enabled: yes
    tags:
      - docker

  - name: Adding user to docker
    user: name='{{ lookup("env", "USER") }}'
          group=docker
    tags:
      - docker

  - name: "Add gpg key for repo"
    rpm_key:
      state: present
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - kernel

  - name: "Enable kernel repo"
    yum:
      name: "https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm"
      state: present
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - kernel

  - name: "Upgrade Kernel"
    yum:
      name: kernel-ml
      enablerepo: elrepo-kernel
      state: present
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - kernel

  - name: "Set Default Kernel to 5.x in grub"
    command: grub2-set-default 0
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - kernel

  - name: Restart server
    command: /sbin/shutdown -r now
    async: 0
    poll: 0
    ignore_errors: true
    tags:
      - kernel
