apiVersion: v1
kind: Namespace
metadata:
  name: powerprotect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: powerprotect
  name: powerprotectadmin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "create", "delete", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpowerprotectadmin
rules:
- apiGroups: [""]
  resources: ["pvc","pv","pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["CustomResourceDefinitions"]
  verbs: ["get", "create", "update", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sapowerprotectadmin
  namespace: powerprotect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sapowerprotectadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: powerprotectadmin
subjects:
- kind: ServiceAccount
  name: sapowerprotectadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterpowerprotectadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterpowerprotectadmin
subjects:
- kind: ServiceAccount
  name: sapowerprotectadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusteradminpowerprotectadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sapowerprotectadmin

