---
apiVersion: "powerprotect.dell.com/v1beta1"
kind: RestoreJob
metadata:
  name: wordpressrestore02
  namespace: powerprotect
spec:
  recoverType: RestoreToNew
  backupJobName: wordpresstest-2020-10-08-16-04-54
  namespaces:
  - name: wordpress
    alternateNamespace: wordpresstest-restored
  persistentVolumeClaims:
  - name: "*"
