---
apiVersion: "powerprotect.dell.com/v1beta1"
kind: RestoreJob
metadata:
  name: originalrestorewordpress01
  namespace: powerprotect
spec:
  recoverType: RestoreToOriginal
  backupJobName: wordpress-2020-10-08-17-52-18
  namespaces:
  - name: wordpress
  persistentVolumeClaims:
  - name: "*"
