---
apiVersion: "powerprotect.dell.com/v1beta1"
kind: RestoreJob
metadata:
  name: biggerspec
  namespace: powerprotect
spec:
  recoverType: RestoreToOriginal
  backupJobName: k8-master02-harbor-2021-01-20-15-38-27
  namespaces:
  - name: k8-master02-harbor
    persistentVolumeClaims:
    - name: "*"
  overwritePvc: true
