apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2020-06-22T15:30:07Z"
  name: sc-common
  resourceVersion: "537018"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/sc-common
  uid: 404f4a28-b49d-11ea-b790-005056808653
parameters:
  fstype: ext4
  storagepolicyname: Space-Efficient
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

